version: '3.7'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: denysitis/labpy4:compose-django
    container_name: django
    networks:
      - public
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.monit
    image: denysitis/labpy4:compose-monitoring
    container_name: monitoring
    depends_on:
      - django
    network_mode: host
    volumes:
      - ./../lab5/server.log:/app/server.log

volumes:
  monit-log:
    driver: local

networks:
  public:
    driver: bridge
